# Generated by Django 5.1.4 on 2024-12-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timestamo',
            new_name='timestamp',
        ),
    ]
